### PR TITLE
fix: incorrect number of audit logs

### LINKED ISSUE #546: [BUG]: incorrect number of audit logs
### Describe the bug

The paginator on Audit logs tab shows wrong number of audit logs.

The reason is, the corresponding query to the DB selects all project audit logs.

### Steps to reproduce

1. Go to Audit logs tab.
2. Scroll down to the table below.
3. Paginator shows the wrong number of audit logs if the number of projects exceeds one.

### Expected behavior

The paginator should show the number that equals the number of audit logs of the current project.

### Screenshots

Untitled

### Additional information

From the screenshot, it can be seen that the paginator states that the number of audit logs being displayed is 6, while in fact, it's 3.

### PR DESCRIPTION
**Pull request by qutluq**
# Description

1) Introduced conditions to prisma and trpc queries so that only audit logs specific to current project are selected.
2) Added helper function generating pagination text, to make code cleaner, and remove duplicate code.
3) Fixed infinite loop render on audit logs page.
4) Added feature that enables pagination to update when Fuse search is used.

Fixes #546 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- OS with version:
- Browser with version:
- SDK / CLI with version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I documented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dahal** [comment]
@qutluq I am running into this issue, current main works perfectly, but there is an issue with this branch. To reproduce this, 
* Logout
* run `yarn db:seed`
* log back in
* create a project
* go to /audits tab

Screen Shot 2023-07-21 at 12 37 18 AM

**Comment by qutluq** [comment]
> @qutluq I am running into this issue, current main works perfectly, but there is an issue with this branch. To reproduce this,
> 
> * Logout
> * run `yarn db:seed`
> * log back in
> * create a project
> * go to /audits tab
> 
> Screen Shot 2023-07-21 at 12 37 18 AM

@dahal I've encountered it too, and been thinking of fixing it in the next PR, but I can commit the fix into this one.

**Comment by qutluq** [comment]
@dahal fixed it with a new commit, please check the PR now, the error should be gone.

**Comment by dahal** [comment]
@qutluq I am now running into this issue. Can you please test by dropping your current DB and recreate migration/seed.

Screen Shot 2023-07-25 at 10 06 40 PM

**Comment by qutluq** [comment]
@dahal there occured an issue, after I reseeded the database, by first dropping it, and creating it again, and then repopulating it with `yarn:db:migrate`, `yarn:db:seed` commands. Now, I can't access localhost:3000:

Screenshot 2023-07-26 121316

I can see that prisma is trying to query, `Access` and `User` tables:
Screenshot 2023-07-26 120746

but these tables are empty:
Screenshot 2023-07-26 120609

**Comment by dahal** [comment]
Please clear your localhost cookies, it should load just fine @qutluq

**Comment by qutluq** [comment]
> Please clear your localhost cookies, it should load just fine @qutluq

Thank you for assistance! It appears that the problem was related to cookies rather than db:seed. Once I cleared the site cookies, I was able to access the website successfully, and the database was populated as expected.

**Comment by qutluq** [comment]
@dahal the issues with member.email and name initials being undefined has been resolved. I verified the solution by dropping the database and recreating it, and everything worked perfectly.

**Review by dahal — APPROVED** [review]
Perfect 💯

**Pull request merged**
